-- Cleanup legacy tables that are blocking enum changes

BEGIN;

-- Drop dependent tables first (in reverse dependency order)
DROP TABLE IF EXISTS "SalesCreditDebitNoteItem" CASCADE;
DROP TABLE IF EXISTS "SalesCreditDebitNote" CASCADE;
DROP TABLE IF EXISTS "SalesInvoiceItem" CASCADE;
DROP TABLE IF EXISTS "SalesInvoice" CASCADE;
DROP TABLE IF EXISTS "SalesApproval" CASCADE;
DROP TABLE IF EXISTS "SalesAuditLog" CASCADE;
DROP TABLE IF EXISTS "SellerKPI" CASCADE;
DROP TABLE IF EXISTS "SalesPriceListItem" CASCADE;
DROP TABLE IF EXISTS "SalesPriceList" CASCADE;
DROP TABLE IF EXISTS "SaleDeliveryItem" CASCADE;
DROP TABLE IF EXISTS "SaleDelivery" CASCADE;
DROP TABLE IF EXISTS "SaleRemitoItem" CASCADE;
DROP TABLE IF EXISTS "SaleRemito" CASCADE;
DROP TABLE IF EXISTS "InvoicePaymentAllocation" CASCADE;
DROP TABLE IF EXISTS "ClientPayment" CASCADE;
DROP TABLE IF EXISTS "ClientLedgerEntry" CASCADE;
DROP TABLE IF EXISTS "StockReservation" CASCADE;
DROP TABLE IF EXISTS "StateTransitionLog" CASCADE;
DROP TABLE IF EXISTS "IdempotencyKey" CASCADE;
DROP TABLE IF EXISTS "ProductionProfile" CASCADE;
DROP TABLE IF EXISTS "DailyProductionEntry" CASCADE;
DROP TABLE IF EXISTS "DocumentSequence" CASCADE;
DROP TABLE IF EXISTS "Cheque" CASCADE;
DROP TABLE IF EXISTS "Shutdown" CASCADE;
DROP TABLE IF EXISTS "ShutdownMilestone" CASCADE;
DROP TABLE IF EXISTS "ShutdownWorkOrder" CASCADE;
DROP TABLE IF EXISTS "SoDMatrix" CASCADE;
DROP TABLE IF EXISTS "SalesConfig" CASCADE;
DROP TABLE IF EXISTS "Warranty" CASCADE;
DROP TABLE IF EXISTS "WarrantyClaim" CASCADE;
DROP TABLE IF EXISTS "ToolConditionLog" CASCADE;
DROP TABLE IF EXISTS "user_whatsapp_groups" CASCADE;
DROP TABLE IF EXISTS "whatsapp_verifications" CASCADE;
DROP TABLE IF EXISTS "daily_production_entries" CASCADE;
DROP TABLE IF EXISTS "disassemble_operations" CASCADE;
DROP TABLE IF EXISTS "production_profiles" CASCADE;
DROP TABLE IF EXISTS "promotion_operations" CASCADE;
DROP TABLE IF EXISTS "MachineFamily" CASCADE;
DROP TABLE IF EXISTS "MachineFamilyLevel" CASCADE;
DROP TABLE IF EXISTS "ProductionLine" CASCADE;
DROP TABLE IF EXISTS "PODUpload" CASCADE;

COMMIT;
